//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4333Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Id { get; set; }
        public string Rent_Code { get; set; }
        public string Date_of_creation { get; set; }
        public string Creation_Time { get; set; }
        public long Client_Code { get; set; }
        public string Servicess { get; set; }
        public string Statuses { get; set; }
        public string Date_of_closing { get; set; }
        public string Rent_time { get; set; }
    }
}
